#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftSlave,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightSlave,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           rightLift,     tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           leftLift,      tmotorVex393_MC29, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port8,           linkageMotor,  tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port9,           clawMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

float countsPerYard = 600;
float countsPerRev = 627.2;
float leftSpeed = 0;
float rightSpeed = 0;
long delayTime = 0;
bool pinch = false;
bool leftTurn = false;
string nums[] = {"zero", "one", "two", "three", "four", "five", "six"};


void LCDManager (const string line1, const string line2) {
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDString(0, 0, line1);
	displayLCDString(1, 0, line2);
}


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	turnLEDOn(redLED);
	turnLEDOff(greenLED);

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(leftSlave);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(rightSlave);
	resetMotorEncoder(linkageMotor);
	resetMotorEncoder(leftLift);
	resetMotorEncoder(rightLift);

	slaveMotor(rightLift, leftLift);
	slaveMotor(leftSlave, leftMotor);
	slaveMotor(rightSlave, rightMotor);

	//Competition-control extension variables
	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;

	while (nLCDButtons != 2 && bIfiRobotDisabled){
		sleep (10);
		LCDManager ("Waiting for", "user input");
	}

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftLift);
	resetMotorEncoder(rightLift);
	resetMotorEncoder(linkageMotor);

	LCDManager("Pre_Autonomous", "Status: Success");

	turnLEDOff(redLED);
	turnLEDOn(greenLED);

	sleep(1000);

	while (bIfiRobotDisabled) {
		LCDManager("Delay (sec)", nums[delayTime]);
		if (nLCDButtons == 1) { // left
			if (delayTime > 0) {
				delayTime -= 1;
			}
		}	else if (nLCDButtons == 4) { // right
			if (delayTime < 6) {
				delayTime += 1;
			}
		}
		while (nLCDButtons == 1 || nLCDButtons == 4) {
			sleep(10);
		}
	}
}

static const float fudgeCountsWhenSomethingsTotallyJankedUp = 1.34;
static const float ticksPerInch = 0.95 * (627.2 / (4.1 * PI));
static const float ticksPerRev = fudgeCountsWhenSomethingsTotallyJankedUp * (ticksPerInch * 15.125 * PI);

//Drive Straight
void straight(float dist, int speed, bool hold)
{
	LCDManager("Straight Move", "");

	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	sleep(200);

	setMotorTarget(rightMotor, dist*ticksPerInch, speed, hold);
	setMotorTarget(leftMotor, dist*ticksPerInch, speed, hold);

	while (!getMotorTargetCompleted(rightMotor) || !getMotorTargetCompleted(leftMotor))
		wait1Msec(10);

}

void turn(float dist, int speed, bool hold)
{
	LCDManager("Turn Move       ", "                ");

	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	setMotorTarget(rightMotor, -dist*ticksPerRev, speed, hold);
	setMotorTarget(leftMotor, dist*ticksPerRev, speed, hold);

	while (!getMotorTargetCompleted(rightMotor) && !getMotorTargetCompleted(leftMotor))
		wait1Msec(10);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	LCDManager("Autonomous", "Beginning");
	sleep(delayTime * 1000);
	///* Stationary
	//straight(3, 30, false);
	//straight(-3, 30, false);
	motor[leftMotor] = 30;
	motor[rightMotor] = 30;
	sleep(800);
	motor[leftMotor] = -30;
	motor[rightMotor] = -30;
	sleep(800);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	sleep(200);
	motor[clawMotor] = 50;
	sleep(1000);
	motor[clawMotor] = -25;
	sleep(1000);
	setMotorTarget(linkageMotor, 7 * -.46 * countsPerRev, 127, true);
	sleep(2000);
	//straight(15, 127 , false);
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;
	sleep(800);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	sleep(50);
	moveMotorTarget(linkageMotor, 3000, 20, true);
	sleep(1500);
	motor[clawMotor] = 50;
	sleep(750);
	motor[clawMotor] = 0;
	//straight(-17, 127, false);
	motor[leftMotor] = -127;
	motor[rightMotor] = -127;
	sleep(1000);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	//*/

	/* Mobile Goal
	setMotorTarget(linkageMotor, 7 * -.44 * countsPerRev, 127, true);
	sleep(500);
	resetMotorEncoder(leftLift);
	resetMotorEncoder(rightLift);
	setMotorTarget(leftLift, 200, 127, true);
	straight(48, 127, true);
	straight(10, 127, true);
	setMotorTarget(leftLift, -2500, 127, true);
	sleep(2000);
	straight(-60, 127, true);
	//*/

	LCDManager("Autonomous", "Completed");
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	turnLEDOn(redLED);
	turnLEDOn(greenLED);
	LCDManager("Driver-Ctlr", "");
	//PID fixup

	nMotorPIDSpeedCtrl[rightMotor] = RegIdle;
	nMotorPIDSpeedCtrl[leftSlave] = RegIdle;
	nMotorPIDSpeedCtrl[leftMotor] = RegIdle;
	nMotorPIDSpeedCtrl[rightSlave] = RegIdle;
	nMotorPIDSpeedCtrl[linkageMotor] = RegIdle;
	nMotorPIDSpeedCtrl[leftLift] = RegIdle;
	nMotorPIDSpeedCtrl[rightLift] = RegIdle;


	while (true)
	{
		leftSpeed = vexRT[Ch3];
		rightSpeed = vexRT[Ch2];

		motor[leftMotor] = leftSpeed;
		//motor[leftSlave] = leftSpeed;
		motor[rightMotor] = rightSpeed;
		//motor[rightSlave] = rightSpeed;

		if (fabs(vexRT[Ch2Xmtr2]) < 10) {
			motor[linkageMotor] = -15;
		} else {
			motor[linkageMotor] = -(vexRT[Ch2Xmtr2] / 2);
		}

		motor[leftLift] = -vexRT[Ch3Xmtr2];

		if (vexRT[Btn7UXmtr2]) {
			motor[clawMotor] = 127;
			pinch = false;
		} else if (vexRT[Btn7DXmtr2]) {
			motor[clawMotor] = -127;
			pinch = true;
		} else if (pinch) {
			motor[clawMotor] = -16;
		} else if (!pinch) {
			motor[clawMotor] = 0;
		}

	}
}
