#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, PIDControl, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port4,           forkMotor1,    tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           forkMotor2,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port6,           rackRotater,   tmotorVex393_MC29, PIDControl, encoderPort, I2C_5)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex393_MC29, PIDControl, encoderPort, I2C_6)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

float countsPerYard = 600;
float countsPerRev = 627.2;
float left = 0;
float right = 0;
bool pinch = false;
int driveSeed = 0;


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(clawMotor);
	resetMotorEncoder(rackRotater);

	slaveMotor(forkMotor2, forkMotor1);
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

}

static const float fudgeCountsWhenSomethingsTotallyJankedUp = 1.11;
static const float ticksPerInch = 0.95 * (627.2 / (4.1 * PI));
static const float ticksPerRev = fudgeCountsWhenSomethingsTotallyJankedUp * (ticksPerInch * 14.375 * PI);

//Drive Straight
void straight(float dist, int speed, bool hold)
{

	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	setMotorTarget(rightMotor, dist*ticksPerInch, speed, hold);
	setMotorTarget(leftMotor, dist*ticksPerInch, speed, hold);

	while (!getMotorTargetCompleted(rightMotor) && !getMotorTargetCompleted(leftMotor))
		wait1Msec(10);

}

void turn(float dist, int speed, bool hold)
{

	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	setMotorTarget(rightMotor, dist*ticksPerRev, speed, hold);
	setMotorTarget(leftMotor, -dist*ticksPerRev, speed, hold);

	while (!getMotorTargetCompleted(rightMotor) && !getMotorTargetCompleted(leftMotor))
		wait1Msec(10);

}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



task autonomous()
{
	straight(10, 50, false);
	straight(-3, 30, false);
	setMotorTarget(clawMotor, -.80 * countsPerRev, -25, false);
	sleep(1000);
	setMotorTarget(rackRotater, -1500, -75, false);
	sleep(500);
	straight(42, 100, false);
	setMotorTarget(rackRotater, -750, 40, false);
	sleep(500);
	setMotorTarget(clawMotor, .50 * countsPerRev, 75, false);
	sleep(1000);
	straight(-10, 100, false);


}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	//PID fixup
	nMotorPIDSpeedCtrl[rightMotor] = RegIdle;
	nMotorPIDSpeedCtrl[leftMotor] = RegIdle;
	nMotorPIDSpeedCtrl[clawMotor] = RegIdle;
	nMotorPIDSpeedCtrl[rackRotater] = RegIdle;

	while (true)
	{

		left = (vexRT[Ch3] * 3) / 4;
		right = (vexRT[Ch2] * 3) / 4;

		// Fork D-Pad
		if (vexRT[Btn8U]) {
			left = -80;
			right = -80;
		} else if (vexRT[Btn8R]) {
			left = 35;
			right = -35;
		} else if (vexRT[Btn8D]) {
			left = 80;
			right = 80;
		} else if (vexRT[Btn8L]) {
			left = -35;
			right = 35;
		}

		// Claw D-Pad
		if (vexRT[Btn7U]) {
			left = 80;
			right = 80;
		} else if (vexRT[Btn7R]) {
			left = -35;
			right = 35;
		} else if (vexRT[Btn7D]) {
			left = -80;
			right = -80;
		} else if (vexRT[Btn7L]) {
			left = 35;
			right = -35;
		}

		motor[leftMotor] = left;
		motor[rightMotor] = right;

		if (fabs(vexRT[Ch2Xmtr2]) < 10) {
			motor[rackRotater] = -15;
		} else {
			motor[rackRotater] = -(vexRT[Ch2Xmtr2] / 2);
		}

		motor[forkMotor1] = -vexRT[Ch3Xmtr2];



		if (vexRT[Btn7UXmtr2]) {
			motor[clawMotor] = 50;
			pinch = false;
		} else if (vexRT[Btn7DXmtr2]) {
			motor[clawMotor] = -50;
			pinch = true;
		} else if (pinch) {
			motor[clawMotor] = -12;
		} else if (!pinch) {
			motor[clawMotor] = 0;
		}

	}
}
