#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, PIDControl, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port4,           forkMotor1,    tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           forkMotor2,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port6,           rackRotater,   tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port7,           clawMotor,     tmotorVex393_MC29, openLoop, encoderPort, I2C_6)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

float countsPerYard = 600;


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	mapEncoderToMotor(leftMotor, I2C_1);
	mapEncoderToMotor(rightMotor, I2C_2);

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	slaveMotor(forkMotor2, forkMotor1);
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

}
void driveTurn(int speed, int waitTime ) {
	motor[rightMotor] = speed;
	wait1Msec(waitTime);
	motor[rightMotor] = 0;
	motor[leftMotor] = -speed;
	wait1Msec(waitTime);
	motor[leftMotor] = 0;
}

void autoFlip () {

}

void driveStraight(int distanceIN, int speed) {
	moveMotorTarget(leftMotor, (distanceIN * (countsPerYard / 36.0)), speed, false);
	moveMotorTarget(rightMotor, (distanceIN * (countsPerYard / 36.0)), speed, false);
}

bool driveStraightComplete() {
	if(getMotorTargetCompleted(leftMotor) && getMotorTargetCompleted(rightMotor)) {
		return true;
		}	else {
		return false;
	}
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task winch()
{
}



task autonomous()
{
	//driveStraight(12, 127);
	//while (!driveStraightComplete()) {

	//}
	//startTask(winch)
	sleep(1000);

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	//PID fixup
	nMotorPIDSpeedCtrl[rightMotor] = RegIdle;
	nMotorPIDSpeedCtrl[leftMotor] = RegIdle;

	while (true)
	{
		motor[leftMotor] = (vexRT[Ch3] * 3) / 4;
		motor[rightMotor] = (vexRT[Ch2] * 3) / 4;

		motor[rackRotater] = vexRT[-Ch2Xmtr2];
		motor[forkMotor1] = vexRT[-Ch3Xmtr2];



		if (vexRT[Btn7UXmtr2]) {
			motor[clawMotor] = 50;
		} else if (vexRT[Btn7DXmtr2]) {
			motor[clawMotor] = -50;
		} else {
			motor[clawMotor] = -5;
		}

	}
}
