#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Motor,  port1,           rotateMotor,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bRackMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           bRackMotor2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rackRotater,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           tRackMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           wristMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

float countsPerYard = 600;
int wristPos = 0;


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	mapEncoderToMotor(leftMotor, I2C_1);
	mapEncoderToMotor(rightMotor, I2C_2);

	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	slaveMotor(bRackMotor2, bRackMotor);
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

}
void driveTurn(int speed, int waitTime ) {
	motor[rightMotor] = speed;
	wait1Msec(waitTime);
	motor[rightMotor] = 0;
	motor[leftMotor] = -speed;
	wait1Msec(waitTime);
	motor[leftMotor] = 0;
}

void autoFlip () {

}

void driveStraight(int distanceIN, int speed) {
	moveMotorTarget(leftMotor, (distanceIN * (countsPerYard / 36.0)), speed, false);
	moveMotorTarget(rightMotor, (distanceIN * (countsPerYard / 36.0)), speed, false);
}

bool driveStraightComplete() {
	if(getMotorTargetCompleted(leftMotor) && getMotorTargetCompleted(rightMotor)) {
		return true;
		}	else {
		return false;
	}
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task winch()
{
	motor[rotateMotor] = 127;
	sleep(1000);
	motor [rotateMotor] = 0;
}



task autonomous()
{
	//driveStraight(12, 127);
	//while (!driveStraightComplete()) {

	//}
	//startTask(winch)
	sleep(1000);

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	while (true)
	{
		motor[leftMotor] = (vexRT[Ch3] * 3) / 4;
		motor[rightMotor] = (vexRT[Ch2] * 3) / 4;

		motor[tRackMotor] = -vexRT[Ch2Xmtr2];

		//motor[clawMotor] = vexRT[Ch1];


		if (fabs(vexRT[Ch3Xmtr2]) > 50) {
			if (vexRT[Ch3Xmtr2] > 0) {
				motor[bRackMotor] = 60;
				} else {
				motor[bRackMotor] = -60;
			}
			} else {
			motor[bRackMotor] = 0;
		}

		if (fabs(vexRT[Ch4Xmtr2]) > 50) {
			if (vexRT[Ch4Xmtr2] > 0) {
				motor[rackRotater] = 30;
				} else {
				motor[rackRotater] = -60;
			}
		} else {
			motor[rackRotater] = -10;
		}

		if (vexRT[Btn8RXmtr2]) {
			if (wristPos > -127) {
				wristPos -= 1;
			}
		} else if (vexRT[Btn8LXmtr2]) {
			if (wristPos < 127) {
				wristPos +=1;
			}
		}
		motor[wristMotor] = wristPos;

		if (vexRT[Btn7UXmtr2]) {
			motor[clawMotor] = 50;
		} else if (vexRT[Btn7DXmtr2]) {
			motor[clawMotor] = -50;
		} else {
			motor[clawMotor] = -5;
		}



		if (vexRT[Btn7RXmtr2]) {
			motor[rotateMotor] = 50;
			} else if (vexRT[Btn7LXmtr2]) {
			motor[rotateMotor] = -50;
			} else {
			motor[rotateMotor] = 0;
		}

	}
}
